nelmio_api_doc:
    documentation:
        info:
            title: Process
            description: Process huge dataset
            version: 1.0.0
    areas:
        path_patterns:
            - ^/process-huge-dataset
