parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\DataService:
        arguments:
            $dsn: '%env(REDIS_DSN)%'
