name: Docker Compose

on:
    push:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Docker Compose
              uses: docker/setup-buildx-action@v3

            - name: Build and start services
              run: docker compose up -d --build

            - name: Install dependencies
              run: docker exec dataset_app composer install --prefer-dist --no-progress

            - name: Run E2E tests
              run: docker exec dataset_app php vendor/bin/phpunit tests/E2E

            - name: Stop services
              run: docker compose down
